name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev, 'feat/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 缓存 Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/daemon
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
            
      - name: 缓存 Android Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/build-cache
            app/build
          key: android-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            android-${{ runner.os }}-

      - name: 配置 JDK 17
      - uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 17
          
      - name: 初始化 Gradle
      - uses: gradle/actions/setup-gradle@v4
      
      - name: 编译 Debug APK
      - run: ./gradlew assembleDebug
      
      - name: 上传 APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk